title:             microbma lab
email:             bma@zju.edu.cn 
description:       exploring wired microbiomes
author:            Bin Ma
url:               "http://microbma.github.io"

# Social Profiles
github_username:   microbma

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
