title:             SysMicro
email:             zhaokk@zju.edu.cn 
description:       Exploring microbial world in a system perspective.
author:            Kankan Zhao
url:               "http://microbma.github.io"

# Social Profiles
github_username:   SysMicro

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
