title:             SysMicro
email:             zhaokk@zju.edu.cn 
description:       System Microbiology: Exploring microbial world in a system perspective.
author:            Kankan Zhao
url:               "http://microbma.github.io"

# Social Profiles
github_username:   SysMicro

# Build settings
markdown:          kramdown
paginate:          5
plugins:
  - jekyll-feed
  - jekyll-paginate
