title:             System Microbiome
email:             kaz026@health.ucsd.edu
description:       Exploring microbial world in a system perspective.
author:            Kankan Zhao
url:               "http://sysmicro.github.io"

# Social Profiles
github_username:   SysMicro

# Build settings
markdown:          kramdown
paginate:          5
plugins:
  - jekyll-feed
  - jekyll-paginate
